### ISSUE TITLE
How do I use this to benchmark my functions?

### ISSUE THREAD

**Issue by LazyHippogriff** [sheredom/ubench.h#1]
I have got 3 files: func.hpp, func.cpp and main.cpp. func.hpp declares 2 functions, func1() and func2(). The implementation is in func.cpp. I want to benchmark these 2 functions. How shall I do it?
I tried the below, but I'm getting various errors:

**func.hpp**
```
#ifndef __FUNC_HPP__
#define __FUNC_HPP__

void func1();
void func2();

#endif
```

**func.cpp**
```
#include "func.hpp"
#include "ubench.h"
#include <iostream>

using namespace std;

void func1() {
  UBENCH(func1,using_cout) {
  cout<<"Hello World"<<endl;
  }
}

void func2() {
  UBENCH(func2,using_printf) {
  printf("Hello World\n");
  }
}
```

**main.cpp**
```
#include "ubench.h"
#include "func.hpp"

UBENCH_STATE();

int main(int argc, char** argv) {
  return ubench_main(argc, argv);
}

```

**Comment by sheredom** [comment]
So how you are defining the benchmarks is the problem - `UBENCH` declares a function itself (because It has to add on a bunch of _other_ code to setup the benchmark registration).

So do:

```c
#include "func.hpp"
#include "ubench.h"
#include <iostream>

using namespace std;

UBENCH(func1,using_cout) {
  cout<<"Hello World"<<endl;
}

UBENCH(func2,using_printf) {
  printf("Hello World\n");
}
```

**Comment by sheredom** [comment]
I tried this locally and got:

```c
name, mean (ns), stddev (%)
func2.using_printf, 85715, 21.147188,
func1.using_cout, 155496, 21.531790,
```

So printf is 44% the cost of cout.
