### ISSUE TITLE
Add Visual Studio / clang-cl testing

### ISSUE THREAD

**Issue by DBJDBJ** [sheredom/ubench.h#8]
I am using clang-cl.exe on Windows.  (that is clang 10)

![image](https://user-images.githubusercontent.com/145155/105625246-f7db1e00-5e27-11eb-9695-67549be512f0.png)

AFAIK `__asm`  is MSVC and `asm` is GCC  .. also with different syntax?

NOTE: I have not tried `-std=gnu99`  (or whatever it is called) and the rest

**Comment by sheredom** [comment]
I've changed the title - I think by adding testing for VS/clang we'll flush out any/all issues :)
